### ISSUE TITLE
Web3 RWA Wallet Dev Roadmap

### ISSUE THREAD

**Issue by Web3HackerWorld** [Web3Hacker-World/Discussions#15]
- [x] rename to Buidlers.Space Wallet?
- [x] a very simple wallet that can import or generate new Mnemonic?
- [ ] focus on token/nft gating feature from Buidlers.Space
- [ ] show current URL relative NFT
- [ ] full detail go to buidlers.space
- [ ] module
  - [ ] content for current url
  - [ ] popup for current domain
  - [x] options page for all data for this wallet
  - [ ] [how metamask store private key](https://www.wispwisp.com/index.php/2020/12/25/how-metamask-stores-your-wallet-secret/)

This app dev also have a book with it!

Web3 RWA Wallet Develop Hand By Hand  https://github.com/Web3Hacker-World/Discussions/issues/22

## discord group
https://discord.gg/AjHkMGfmbU

## wechat group
<img src="https://github.com/Web3Hacker-World/Discussions/assets/109504677/14abf5c6-3a21-4766-8786-fe7340a84472" width="400" />

**Comment by Web3HackerWorld** [comment]
- [x] Options Page UI
  - [x] index
  - [x] onboard
    - [x] create-password
  - [x] [tokenId]
- [x] Injected Content UI
  - [x] add inject content to any page
  - [x] two buttons: list btn, create btn
  - [x] list tab list
  - [x] create NFT / create content

https://github.com/parity-asia/hackathon-2023-summer/pull/9

**Comment by Web3HackerWorld** [comment]
- [x] onboard
  - [x] index
  - [x] create-password
  - [x] review-recovery-phrase
  - [x] confirm-recovery-phrase
  - [x] completion
    - [x] firework
  - [x]  login
  - [x] import-wallet

**Comment by Web3HackerWorld** [comment]
- [ ] injected module
  - [ ] new
    - [ ] new NFT
      - [x] fix resize-textarea bug
      - [x] add rwa-js-sdk utils: 
      - [x] fix img flex layout
      - [x] new nft form
    - [x] RWA-JS-SDK
    - [ ] new Content
